baseURL: "https://dilfal.github.io/"
title: difal
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: ":uk:"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
#                 - name: WiKi
#                  url: https://dilfal.github.io/
#                - name: Discord
#                  url: https://discord.gg/

    it:
        languageName: ":it:"
        languageAltTitle: Italiano
        weight: 2
        title: dilfal
        taxonomies:
          category: categorie
          tag: tag
          series: serie
        menu:
            main:
                - name: Archivio
                  url: archives/
                  weight: 5
                - name: Tag
                  url: tag
                  weight: 10
                - name: Categorie
                  url: categorie
                  weight: 10
                - name: Serie
                  url: serie
                  weight: 10
#                - name: NullLink
#                  url: "#"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "ExampleSite description"
    keywords: [Blog, Portfolio]
    author: DF
    # author: ["Me", "You"] # multiple authors
    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 January 2006"

# profile-mode
    profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
    homeInfoParams:
        Title: "dilfal"
        Content: >
            Welcome to dilfal's site 🖖🏻

            - **dilfal** contains some guides, click on the flag to change languages and on the sun/moon to change theme.

            - Site's theme: [PaperMod](https://github.com/adityatelange/hugo-PaperMod).

    socialIcons:
        - name: github
          url: "https://github.com/dilfal"
        - name: Rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/dilfal/dilfal.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html

fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

    label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
